
---
apiVersion: batch/v1
kind: Job
metadata:
  name: honeycomb-geom-processor-prepare-2019-01-17
  namespace: honeycomb
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: honeycomb-role
    spec:
      containers:
      - name: migrate
        image: wildflowerschools/honeycomb-geom-processor:prepare-v0
        envFrom:
          - secretRef:
              name: honeycomb-client-settings
        env:
        - name: ENVIRONMENT_NAME
          value: capucine
        - name: START_TIME
          value: 2019-12-06T13:00
        - name: END_TIME
          value: 2019-12-06T22:00
        - name: SOURCE
          value: cuwb
      restartPolicy: OnFailure
  backoffLimit: 4

