
---
apiVersion: batch/v1
kind: Job
metadata:
  name: honeycomb-geom-processor-prepare-2020-01-17-cuwb
  namespace: honeycomb
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: honeycomb-role
    spec:
      containers:
        - name: geom-processor-prepare
          image: wildflowerschools/honeycomb-geom-processor:prepare-v1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: honeycomb-client-settings
            - configMapRef:
                name: honeycomb-geom-processor-timescaledb-client-config
          env:
            - name: ENVIRONMENT_NAME
              value: capucine
            - name: START_TIME
              value: 2020-01-17T13:00
            - name: END_TIME
              value: 2020-01-17T22:00
            - name: SOURCE
              value: cuwb
      restartPolicy: OnFailure
  backoffLimit: 4
